version: '3.4'
services:
  dashboard:
    restart: unless-stopped
    container_name: dashboard
    stdin_open: true
    tty: true
    ports:
      - 8080:8080
      - 8000:8000
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/src
      - /etc/localtime:/etc/localtime
